#!/bin/sh
#
# Removes all stuff generated by cmake / make
#
# This mini script supposes an inplace build.
#
rm -rf build/ CMakeFiles/

rm -f \
	AdditionalInfo.txt \
	config.h \
	Makefile \
	CMakeCache.txt \
	cmake_install.cmake \
	install_manifest.txt \
	signames.lua \
	default.c \
	core.c \
	*.o \
	*.out \
	core/*.o \
	lsyncd
